### ISSUE TITLE
在新的电脑上运行时 Parser 无法正常工作

### ISSUE THREAD

**Issue by NN708** [obstudio/QingyunMusicPlayer-WL#16]
目前已有 3 例（ @Track07-cda @Anemonefish01 电脑上都出现了该问题）在之前没有运行过 QYMP 的电脑上出现 Parser 无法正常工作的情况（可能是 Audio[] 不能正常工作）。
是不是在使用 Audio[] 之前还需要做什么初始化工作？

**Comment by shigma** [comment]
这个不属于程序编写问题，推测是Mathematica故障

**Comment by shigma** [comment]
建议让安装的电脑先试运行AudioPlay[Audio[SoundNote[0,1]]];
如果不行说明Mathematica有问题，就不要用QYMP了@nn708

**Comment by shigma** [comment]
目前可以使用MIDI绕过Audio，这个问题暂时告一段落吧。

**Comment by NN708** [comment]
经过我的研究，一个极有可能的原因就是用户名称中使用了中文字符，在 AppData 下的文件路径中出现乱码无法读取，导致 Audio 函数无法正常调用。同时 ExternalEvaluate 无法使用的问题也有可能是这样导致的。

请大家结合自己使用的情况，验证一下上述判断是否正确。

**Comment by shigma** [comment]
@nn708 目前没有找到实例证明这件事.
倒是我的一个同学用英文路径, 却也无法使用 ExternalEvaluate.
你有进一步的证据吗?

**Comment by NN708** [comment]
只是一个猜测，可能不太正确。现在需要更多的情况来分析这个问题。

**Comment by shigma** [comment]
如果是 Mathematica 本身的问题的话, 我们会考虑体系上绕过的, 该问题本身不会解决了.
