### ISSUE TITLE
更改一些涉及拍数计算的处理

### ISSUE THREAD

**Issue by shigma** [obstudio/QingyunMusicPlayer-WL#25]
- [x] `Tremolo2`：如果subtrack1或2中含有pre和post，那么返回的音轨也应对应地进行处理。
- [x] `Portamento`：如果subtrack1或2中含有pre和post，那么返回的音轨也应对应地进行处理。
- [x] `Tuplet`：若读入的音轨有pre和post，则对应的拍数也应对应地进行处理。
- [x] `/x:`和`/`：由于它也是小节线的一种，应补上对于小节拍数的判定。

**Comment by NN708** [comment]
函数调用时的参数是 Parser 处理后的子音轨，已经不含有小节线。对于拍数的判定是在函数调用之前（具体说来是在函数参数解析时）完成的，因此 `Tremolo2` 和 `Portamento` 这两点是不成立的，请修改一下。

**Comment by shigma** [comment]
@nn708 我已经修改了，谢谢提醒。

**Comment by jjyyxx** [comment]
对于比较合理的用例现已能正常支持
如：（意会）{1}\~{2---^|2---|}
但诸如{|1}\~{2}之类的古怪情况，我认为不属于合理tok的范畴，导致程序讨论起来十分复杂，故暂不支持。
如有错误，请指正。

**Comment by shigma** [comment]
@jjyyxx 你说的这个问题我跟@nn708 讨论过了。
非常抱歉的是，我们目前认为我们对`Portamento`的语法需要更正。
`Portamento (subtrack1, subtrack2)`用于表示两个音符之间的滑音。输入的应该是两个各含有一个音符的子音轨（多余一个的话将报错(post2.0)），输出一个子音轨。不同的是。子音轨中分为**滑音部分和单音部分**。
滑音部分算法与目前相同，但持续时值仅为subtrack1的时值。
单音部分即为subtrack2本体。（这是添加的部分！）
综上所述，滑音的持续时值无论如何将等于subtrack1+subtrack2。因此，将subtrack1和subtrack2中对应的pre和post作为返回子音轨的meta传出是没有问题的。
基于上述观点，你所说的“古怪”已经不存在了。如果还有问题，请进一步提出。

**Comment by jjyyxx** [comment]
1. 那么Tremolo2也有类似规定？
2. Port的输入子音轨中是否允许连音线

**Comment by shigma** [comment]
@jjyyxx 您好！一大早上写程序真是辛苦了！
1. 有关Tremolo2，经过研究发现，双震音的参数应该是由两个时值相同的音符（如果不相同则报错post2.0）。而程序在处理时无论如何只会关心右侧的音符的时值。因此双震音函数的返回pre和post只与subtrack2有关。
2. 有关Portamento输入子音轨的连音线问题。应当认为这种情况是存在的，例如下面的情形：
```135~1^|%---|```
如果对于这类情形的处理会有问题，请联系我。

**Comment by shigma** [comment]
@jjyyxx 您好！经过我和@nn708 的讨论，认为现在`Tuplet`函数的算法并不够好，可能需要在2.0版本前更改。目前的函数是这样实现的：
```JavaScript
const scale = Math.pow(2, Math.floor(Math.log2(expr))) / expr
const t = new SubtrackParser(subtrack, this.Settings, this.Libraries, this.pitchQueue).parseTrack()
t.Content.forEach((note) => {
    note.__oriDur *= scale
    note.Duration *= scale
    note.StartTime *= scale
})
t.Meta.Duration *= scale
if (t.Meta.Single) {
    t.Meta.Incomplete[0] *= scale
} else {
    t.Meta.Incomplete[0] *= scale
    t.Meta.Incomplete[1] *= scale
}
return t
```
而我们认为更好的处理方式实际上更加简单，只需先将`this.Settings`中的`Duration`参数改成原来的`scale`倍，再以此为参数调用`TrackParser`即可。你认为这种做法是否可以呢？

**Comment by jjyyxx** [comment]
非常感谢您对我的算法提出宝贵意见！我认为这一优化的思路十分巧妙，但在具体实现时还是有两个问题：

1. 目前，`Duration`这一设置直接存储`Dur(x)`中的x值，想要使`Duration`保持正确，可能**需要**`this.Seetings.Duration -= Math.log2(scale)`，**或者**将`Duration`改造为存储2^(-x)，并适当更改整体逻辑。

2. 如果三连音的子音轨中出现了`Dur(x)`的调用，有可能导致结果不正确。
