### ISSUE TITLE
几个需要紧急处理的bug

### ISSUE THREAD

**Issue by shigma** [obstudio/QingyunMusicPlayer-WL#26]
- [x] 特定情况下pitchQueue报错（怀疑是parser未同步）。
样例：`<Piano>(Oct:-3)(84%)(6~){5o%%%%%}|4#(1=)4'#---|`

- [x] 有的音被延长到了当前音轨的最后。
样例：`<PanFlute>(2^)3---^|%---|0---|0---|`

- [x] `%` 的传递问题，希望能在一个音轨（暂时不跨音轨或乐章）中按时间顺序（程序执行的时间顺序，即在子音轨中就是播放的时间顺序，在函数中则是参数从左至右的顺序）传递，无论是否穿过子音轨

**Comment by jjyyxx** [comment]
No.2的样例不可复现该bug。

**Comment by shigma** [comment]
@jjyyxx 一个错误案例：
```
(4/4)(1=#C)(140)

<Violin>(Dur:1){
[52'][64'][7b2'5'][27b]'[7b2'5']-[7b5'][64']|[67b2'5']-------|
[52'][64'][7b2'5'][27b]'[7b2'5']-[7b5'][64']|[562']-------|
[52'][64'][7b2'5'][27b]'[7b2'5']-[7b5'][64']|[25']-(1''#^)[42']'-[15]'-[61'4']-|
/1:[3b5']7'b1''2''5'4'[42'][464']|[57b5']-------|
/2:(110)[3b5']7'b1''2''5'4'(80)[42'][464']|(Dur:0)(110)[57b5']---^|%---}
```

**Comment by shigma** [comment]
第一个问题是我的问题，目前已修复，

**Comment by shigma** [comment]
第二个问题应该也是由MMA内部机制导致的，目前采用了“绕过去”这一治标不治本的做法，算是暂时解决了。
