### ISSUE TITLE
将子音轨反复中的 / 记号改为 \

### ISSUE THREAD

**Issue by NN708** [obstudio/QingyunMusicPlayer-WL#29]
由于历史原因，`\` 字符被用于将下一行连接到上一行，因此子音轨反复中使用了 `/` 记号。但在数学中 `\` 表示“除了”，更好地体现了子音轨反复中“除去这一部分不播放”的意思。目前原有 `\` 记号已取消，因此建议将 `/` 改为 `\`，之后将 `/` 用于子音轨重叠的功能。

**Comment by Shigma** [comment]
@nn708 需要在2.0发布前完成吗？
