### ISSUE TITLE
增加几个反复记号

### ISSUE THREAD

**Issue by NN708** [obstudio/QingyunMusicPlayer-WL#30]
几个反复记号需要实装：
<table>
<thead>
<tr>
<td><b>记号</b></td>
<td><b>Token Type</b></td>
</tr>
</thead>
<tbody>
<tr>
<td>+</td>
<td>Coda</td>
</tr>
<tr>
<td>s</td>
<td>Segno</td>
</tr>
<tr>
<td>DC</td>
<td>DaCapo</td>
</tr>
<tr>
<td>DS</td>
<td>DaSegno</td>
</tr>
</tbody>
</table>

一个反复记号混合使用的实例：
![316124_1](https://user-images.githubusercontent.com/20534082/36942018-55f542e2-1fa4-11e8-8973-dc80eed4762c.gif)

**Comment by shigma** [comment]
目前 Tokenizer 已经完全实现。
如果这方面遇到问题，可以找我。

**Comment by NN708** [comment]
上述功能 Parser 已全部实现。

同时建议再添加一个符号 Fine，Token Type 也为 Fine，表示大反复第二遍的全曲结束点。

**Comment by NN708** [comment]
Parser 已实现 Fine
