### ISSUE TITLE
报错系统初步

### ISSUE THREAD

**Issue by shigma** [obstudio/QingyunMusicPlayer-WL#31]
建立报错系统的雏形，并实现基本的系统报错。

利用新的报错系统和规定的报错规范完成：

- Note 相关
  - [x] Note::ChordRange 计算和弦时出现错误的范围
  - [x] Note::Reduplicate 和弦内存在重复的音
  - [x] Note::OutOfRegister 某一个音超出音域
  - [x] Note::NoPrevious 使用%时缺乏前置音符
  - [x] Note::VolumeLimit 音量超过上限

- Track 相关
  - [x] Track::BarLength 小节长度错误
  - [x] Track::Instrument 声明了不存在的乐器
  - [x] Track::Undefined 发现了未知字符
  - [x] Track::Overlay 各Overlay部分的长度不一致

- Sect 相关
  - [x] Sect::DiffDuration 各音轨长度不同
  - [x] Sect::InitiativeBar 各音轨的起始小节不等长
  - [x] Sect::Mismatch 相邻乐章的起始小节与终止小节不匹配

**Comment by jjyyxx** [comment]
超出音高暂未实现（各乐器音高范围无法获取），其余已经完成

**Comment by shigma** [comment]
@jjyyxx 辛苦了。音高问题我们稍后在讨论一下吧。

**Comment by jjyyxx** [comment]
如果有bug可以重启issue
