### ISSUE TITLE
实装 Overlay 符号 /

### ISSUE THREAD

**Issue by NN708** [obstudio/QingyunMusicPlayer-WL#34]
目前原有的子音轨反复记号已改为 \，因此可以实装 Overlay 符号 /。
该符号 Token Type 为 Barline，增加一布尔属性 Overlay 来表示。
在 Parser 中的处理即为将当前子音轨时间归零，以达到重叠的效果。当各重叠部分长度有一个以上不相等时，扔出一个 Warning。

**Comment by jjyyxx** [comment]
Warning统一置入报错系统处理，基本支持完成。
