### ISSUE TITLE
Template Subtracks

### ISSUE THREAD

**Issue by shigma** [obstudio/QingyunMusicPlayer-WL#42]
目前的音轨头被允许在乐器后面任意地跟上函数 (当然仅仅是函数), 作为一个音轨的预处理部分. 那么如果要使用多个乐器共用的音轨中设置部分乐器的和弦环境, 又如何处理呢? "模板音轨"提供了一种解决方案.

模板音轨与正常的音轨语法完全相同, 但其中可能包含某种特定的宏音轨 (虽然不应该这么叫, 但是姑且这么说吧), 以保留字的形式呈现, 比如`@0`或者`@_`或者`@this`这样的 (还没定下来, 我就先以第一个为例了~)

正如你所见的那样, 模板音轨其实可以作为一个纯函数. 当它被调用时, 如果含有对应的参数, 则将该参数赋给当前的`@0`后执行. (具体的实现究竟是纯函数, 还是实体函数, 我个人认为都是可以的.)

那么在一个音轨的音轨头中, 如果我们允许函数和模板音轨, 并将函数组合理解成模板音轨处理, 那么就能够解决开始的问题了, 比如:
`<Piano (100%) Oct(1)>`  => `<Piano {(100%) Oct(1) @0}>`
(这是程序的自然解读方式, 因而保证了兼容性.)

这样一来, 模板音轨`{(100%) Oct(1) @0}`才是这个音轨的本体, 当执行时将音轨的内容作为`@0`本身来处理, 于是我们就允许对于音轨整体进行更丰富的操作了.

下面是一个例子 (使用了`@this`):
```
<:env:> (80%) Dur(1) 1>51'51'5

< Guitar {(72%) Rest(24) @env: Oct(-1) @this},
  Strings {(60%) Oct(-2) Con(-1,0.8) @this @this},
  SlapBass {(64%) Oct(-3) Stac(1/2, 0) @this @this}
> 6--^|%--^|%--|7--|1'--^|%--|4--|5--|
```
这样就将三个相似但完全不同的音轨统一地表示了.

**Comment by NN708** [comment]
感谢 @Shigma 的提案。

但我经过思考认为模板音轨的实现意义不大，理由如下：

1. 就语法本身而言，模板音轨并不能做到比一般记法简便快捷。如 @Shigma 提到的例子：
```
<:env:> (80%) Dur(1) 1>51'51'5

< Guitar {(72%) Rest(24) @env: Oct(-1) @this},
  Strings {(60%) Oct(-2) Con(-1,0.8) @this @this},
  SlapBass {(64%) Oct(-3) Stac(1/2, 0) @this @this}
> 6--^|%--^|%--|7--|1'--^|%--|4--|5--|
```
这个例子完全可以用已有的一般记法来写：
```
<:env:> (80%) Dur(1) 1>51'51'5
<:a:> 6--^|%--^|%--|7--|1'--^|%--|4--|5--|

<Guitar(72%)> Rest(24) @env Oct(-1) @a

<Strings{(60%) Oct(-2) Con(-1,0.8)}, SlapBass{(64%) Oct(-3) Stac(1/2, 0)}> @a @a
```
而且普通记法反而更加简便。

2. 模板音轨的逻辑性较差。我们将音轨头分离的原因并不是与我们的程序处理有关，而是更加符合用户的使用习惯，即可以一目了然地看出哪些是音轨设置，哪些是音轨（音符）本身。如上述两种记法中，后者显然更加清晰地体现了 `Rest(24) @env @a` 都是有意义的音符音轨（这里还要说一下，`Rest()` 因为有时值，所以也是有意义的音轨，不应在音轨头中出现）。同时，和 @Shigma 所说的一样，模板音轨是将“相似但完全不同的音轨统一地表示”，但它们本来就是不同的，只是强行将其统一表示，而且也不是明显地表示出其相似部分，所以对用户而言也是不太好的体验。
此外，并不是所有内容都应该出现在音轨头中。如给不同的乐器设置不同的速度，虽然在程序处理上没有任何问题，但在播放上显然是不合逻辑的，会导致报错。因此，对音轨头的内容加以限制显然是需要的，并不能因为是“程序的自然解读方式”就认为任何内容都可以出现在音轨头中。

3. 模板音轨的动态性并不强。从模板音轨的起源上来讲，它来源于 C++ 中的 template，而 C++ 的 template 是为了弥补 C++ 作为编译执行的语言所造成的无法动态生成函数的问题而出现的。而我们的 TM 语言在执行过程中一切是动态的，如反复中可以转调，动态性本来就很强，可以这么说，模板音轨的动态性并不比现有的一般记法强。而且 C++ 的 template 本身就有语法复杂、不易使用的问题，我们现在的模板音轨也同样产生了这样的问题。
而且，我们还有全动态的函数，解决各种动态问题都是游刃有余。官方包编写后，使用起来将是极其方便的，必然比模板音轨要方便、易用得多。对于和弦环境的问题，@Shigma 没有给出详细的例子，我在这里也就不再详细展开了。

综上所述，模板音轨的意义不大，目前可以暂不考虑实现模板音轨。

以上是我个人的一点拙见，希望大家能进一步深入思考，谢谢！

**Comment by shigma** [comment]
@nn708 既然你说暂时不考虑实现, 那我也先听取你的意见, 然而你所说的论点却完全不能说服我.
1. 从记法上说的方便快捷并不是程序本身的唯一需求, 想法也是很重要的. 比如当一切都能通过函数和包封装的时候为什么会有面向对象语言? 虽然有很多原因, 但是显然"同类合并"也是一个重要的推动力. 很多时候对象化并不能帮程序减少长度 (这也是很多计算机语言学家所吐槽的重点所在), 但如果把东西弄得非常零散, 是不符合模块化思维的. 
2. 你说的 C++ 的例子也从侧面反映了这一点. C++ 是什么? 那不过是在 C 的基础上做了些许力所能及的补充罢了, 它的模板思维与我的设计完全没有一点关系, 你这么说正好反应了某些过度追求速度, 而丧失了设计思想的观点.
3. 模板音轨是的音轨头的逻辑性增强了. 原来的音轨头的设计让人难以捉摸那是什么. 现在我却可以明确地定义音轨头就是音轨的本体. 一切函数可以写在前面也可以写在后面. 比如过去如果要专门对于某种乐器进行淡出, 就不得不把改乐器的`FadeOut`写在最前面, 这显然是没有逻辑的体现. 而当使用模板音轨记录信息时, 其内部存在的音符, `Rest`等内容就是音轨本身, 在前在后加入渐强渐弱也显得自然.
4. 另一方面, 音轨头中的`{...}`记号没有任何意义, 而且会导致用户理解出现偏差. 比如写`(100%)`和`{(100%)}`在音轨头, 从逻辑的角度来说应该是不同的, 但是却得到了相同的结果, 这是我们无论如何也不能接受的语法漏洞. 因此, **就算模板音轨的设计不好, 我们弃之不用, 也应放弃音轨头嵌入音轨的记号, 只允许写函数.**

**Comment by NN708** [comment]
好，这个问题我们以后再讨论。
