### ISSUE TITLE
修复播放界面播放进度时间无法正常显示的问题

### ISSUE THREAD

**Issue by NN708** [obstudio/QingyunMusicPlayer-WL#47]
当前显示为：
![image](https://user-images.githubusercontent.com/20534082/38810784-627f0448-41ba-11e8-94c9-b4cd80b7123d.png)

**Comment by shigma** [comment]
无法复现. 希望给出明确的错误触发方法以及堆栈跟踪.

**Comment by NN708** [comment]
![image](https://user-images.githubusercontent.com/20534082/39001756-9e6423d2-4429-11e8-9c8e-754b7833ab71.png)
正常播放时即会出现。

**Comment by shigma** [comment]
情况已经了解, 但是究竟如何产生仍然未知. 目前我个人从未出现类似的情况. 
如果该情况发生多例或者发现进一步的线索请进一步联系我. 

为程序可能存在的错误表示抱歉.
以上.

**Comment by shigma** [comment]
发现问题来源涉及 UnitConvert 函数，暂时提供了联网的解决方案。
