### ISSUE TITLE
buffer.json 哈希值存储问题

### ISSUE THREAD

**Issue by NN708** [obstudio/QingyunMusicPlayer-WL#48]
当前音乐加载失败后，buffer.json 仍会正常存储哈希值，导致之后播放器中报错，希望能够解决。另外，希望播放前做 buffer 文件是否存在的检测，若文件不存在则进行友好的提示。

**Comment by shigma** [comment]
情况已经了解. 感谢您的反馈. 目前的处理方法为:
1. 当文件生成遇到错误时会自动删除对应的 hash 值.
2. 当播放未正确缓存的歌曲时会自动停止播放回到上一页面.
