### ISSUE TITLE
关于在更新的Wolfram版本上使用

### ISSUE THREAD

**Issue by asdasd1dsadsa** [obstudio/QingyunMusicPlayer-WL#57]
自己排除了几个问题以后，发现在处理JS返回的结果时，Duration之类的键值读不到，似乎返回的结果与你们当时设计时考虑的已经结构不同了。

是因为ExternalEvaluate_NodeJS的版本更新了，行为不同了么？

**Comment by NN708** [comment]
@asdasd1dsadsa 你好！

感谢你反馈这个问题。我用 Wolfram Mathematica 12.1 测试了一下，确实出现了 Parser 无法返回结果的情况。

经过排查，发现在 Mathematica 调用 [`Thulium.js`](https://github.com/obstudio/ThuliumMusic-WL/blob/7daa4ca1001cdd1e1e995d3282536a2691ebae66/library/Thulium.js) 时，相对路径无法使用了，应该是 `ExternalEvaluate[]` 的行为出现了一些改动。在将 `Parser`、`Tokenizer`、`Linter` 和 `packagePath` 全部改成绝对路径之后，暂时就可以正常运行了，你可以先尝试一下。

**Comment by asdasd1dsadsa** [comment]
啊，我突然发现，我当时搞不出来是因为测试的时候忘记调用parse方法了，所以返回的结果跟AudioAdapt函数要求的格式不一样（众所周知，百思不得其解的问题都是低级问题……）
现在改好路径以后确实可以用了。

**Comment by NN708** [comment]
已在 8c8d79e4df192917827db684133c4bbf3c7e80cf 中修复。
